const HTTP_OK_STATUS = 200;
const HTTP_ERROR_STATUS = 500;
const HTTP_NOT_FOUND = 404;
const HTTP_BAD_REQUEST = 400;
const HTTP_CREATED_STATUS = 201;
const PORT = process.env.PORT || '3001';
const TALKER_JSON = './src/talker.json';

module.exports = {
  HTTP_OK_STATUS,
  HTTP_ERROR_STATUS,
  HTTP_CREATED_STATUS,
  HTTP_NOT_FOUND,
  HTTP_BAD_REQUEST,
  PORT,
  TALKER_JSON,
};
